controller:
  numExecutors: 10
  adminUser: "admin"
  # adminPassword: <defaults to random>
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  # For minikube, set this to NodePort, elsewhere use LoadBalancer
  # Use ClusterIP if your setup includes ingress controller
  serviceType: ClusterIP
  ingress:
    enabled: false
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "extensions/v1beta1"
    hostName: jenkins.example.com
    tls:
    - secretName: jenkins-tls
      hosts:
        - jenkins.example.com

  installPlugins:
    - kubernetes:1.29.0
    - workflow-aggregator:2.6
    - git:4.5.2
    - configuration-as-code:1.47
    - saml:1.1.7
    - matrix-auth:2.6.5

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: "8Gi"

rbac:
  create: true
  readSecrets: false

serviceAccount:
  create: true
  name: jenkins
